#!/usr/bin/python

import argparse

parser = argparse.ArgumentParser(
    description="Generate C source for stub IRQ handlers (ISRs)")
parser.add_argument('--irqs', type=int, default=240,
    help='Number IRQs')
parser.add_argument('out',
    help='Output file with the generated C source')
args = parser.parse_args()

f = open(args.out, "w")

f.write(
"""
/* This file was automatically generated by genisr.py.
 *
 * The following define stub functions that are called by the IRQ handlers
 * defined in assembly in vectors.s (generated by genvec.py).
 */
""")

f.write(
"""
#include "uart.h"
""")

for i in range(0, args.irqs):
    f.write(
"""
int irq%u (void) {
    puts("IRQ %u\\n");
    return(0);
}
""" % (i, i))
