#include "mailbox-link.h"
#include "printf.h"

#define MBOX_ISR(b, i) MBOX_ISR_INNER(b, i)
#define MBOX_ISR_INNER(b, i) \
        void mbox_ ## b ## _ ## i ## _rcv_isr() { printf("b %u i %u mp %p m %p\r\n", b, i, &mboxes[b][i], mboxes[b][i]); mbox_rcv_isr(mboxes[b][i]); } \
        void mbox_ ## b ## _ ## i ## _ack_isr() { printf("b %u i %u mp %p m %p\r\n", b, i, &mboxes[b][i], mboxes[b][i]); mbox_ack_isr(mboxes[b][i]); }

MBOX_ISR(MBOX_BLOCK_HPPS, 0);
MBOX_ISR(MBOX_BLOCK_HPPS, 1);
MBOX_ISR(MBOX_BLOCK_HPPS, 2);
MBOX_ISR(MBOX_BLOCK_HPPS, 3);
MBOX_ISR(MBOX_BLOCK_HPPS, 4);
MBOX_ISR(MBOX_BLOCK_HPPS, 5);
MBOX_ISR(MBOX_BLOCK_HPPS, 6);
MBOX_ISR(MBOX_BLOCK_HPPS, 7);
MBOX_ISR(MBOX_BLOCK_HPPS, 8);
MBOX_ISR(MBOX_BLOCK_HPPS, 9);
MBOX_ISR(MBOX_BLOCK_HPPS, 10);
MBOX_ISR(MBOX_BLOCK_HPPS, 11);
MBOX_ISR(MBOX_BLOCK_HPPS, 12);
MBOX_ISR(MBOX_BLOCK_HPPS, 13);
MBOX_ISR(MBOX_BLOCK_HPPS, 14);
MBOX_ISR(MBOX_BLOCK_HPPS, 15);
MBOX_ISR(MBOX_BLOCK_HPPS, 16);
MBOX_ISR(MBOX_BLOCK_HPPS, 17);
MBOX_ISR(MBOX_BLOCK_HPPS, 18);
MBOX_ISR(MBOX_BLOCK_HPPS, 19);
MBOX_ISR(MBOX_BLOCK_HPPS, 20);
MBOX_ISR(MBOX_BLOCK_HPPS, 21);
MBOX_ISR(MBOX_BLOCK_HPPS, 22);
MBOX_ISR(MBOX_BLOCK_HPPS, 23);
MBOX_ISR(MBOX_BLOCK_HPPS, 24);
MBOX_ISR(MBOX_BLOCK_HPPS, 25);
MBOX_ISR(MBOX_BLOCK_HPPS, 26);
MBOX_ISR(MBOX_BLOCK_HPPS, 27);
MBOX_ISR(MBOX_BLOCK_HPPS, 28);
MBOX_ISR(MBOX_BLOCK_HPPS, 29);
MBOX_ISR(MBOX_BLOCK_HPPS, 30);
MBOX_ISR(MBOX_BLOCK_HPPS, 31);

MBOX_ISR(MBOX_BLOCK_LSIO, 0);
MBOX_ISR(MBOX_BLOCK_LSIO, 1);
MBOX_ISR(MBOX_BLOCK_LSIO, 2);
MBOX_ISR(MBOX_BLOCK_LSIO, 3);
MBOX_ISR(MBOX_BLOCK_LSIO, 4);
MBOX_ISR(MBOX_BLOCK_LSIO, 5);
MBOX_ISR(MBOX_BLOCK_LSIO, 6);
MBOX_ISR(MBOX_BLOCK_LSIO, 7);
MBOX_ISR(MBOX_BLOCK_LSIO, 8);
MBOX_ISR(MBOX_BLOCK_LSIO, 9);
MBOX_ISR(MBOX_BLOCK_LSIO, 10);
MBOX_ISR(MBOX_BLOCK_LSIO, 11);
MBOX_ISR(MBOX_BLOCK_LSIO, 12);
MBOX_ISR(MBOX_BLOCK_LSIO, 13);
MBOX_ISR(MBOX_BLOCK_LSIO, 14);
MBOX_ISR(MBOX_BLOCK_LSIO, 15);
MBOX_ISR(MBOX_BLOCK_LSIO, 16);
MBOX_ISR(MBOX_BLOCK_LSIO, 17);
MBOX_ISR(MBOX_BLOCK_LSIO, 18);
MBOX_ISR(MBOX_BLOCK_LSIO, 19);
MBOX_ISR(MBOX_BLOCK_LSIO, 20);
MBOX_ISR(MBOX_BLOCK_LSIO, 21);
MBOX_ISR(MBOX_BLOCK_LSIO, 22);
MBOX_ISR(MBOX_BLOCK_LSIO, 23);
MBOX_ISR(MBOX_BLOCK_LSIO, 24);
MBOX_ISR(MBOX_BLOCK_LSIO, 25);
MBOX_ISR(MBOX_BLOCK_LSIO, 26);
MBOX_ISR(MBOX_BLOCK_LSIO, 27);
MBOX_ISR(MBOX_BLOCK_LSIO, 28);
MBOX_ISR(MBOX_BLOCK_LSIO, 29);
MBOX_ISR(MBOX_BLOCK_LSIO, 30);
MBOX_ISR(MBOX_BLOCK_LSIO, 31);
