# GNU ARM Embedded Toolchain (min version required for RTPS: 7-2018-q2-update)
# Either add toolchain install dir to PATH or override this var
CROSS_COMPILE ?= arm-none-eabi-

BLDDIR = bld
SUBDIRS = \
	lib \
	drivers \
	plat \
	plat/console \
	test \
	tests \

define dirrule
$(BLDDIR)/$(1):
	mkdir -p $$@
endef
$(foreach d,$(SUBDIRS),$(eval $(call dirrule,$(d))))

define cfg-or
$(if $(filter-out 0,$(strip $(1))),1,0)
endef

dirs: | $(addprefix $(BLDDIR)/,$(SUBDIRS))
