# Enable/disable standalone tests here:
TEST_FLOAT 						= 1
TEST_SYSTICK					= 1
TEST_WDTS 						= 1
TEST_TRCH_DMA					= 1
TEST_TRCH_DMA_CB 				= 1 # if set, use callback, otherwise call dma_wait
TEST_RT_MMU						= 1
TEST_ETIMER						= 1
TEST_RTI_TIMER					= 1
TEST_SHMEM						= 1

# Set build configuration here
CONFIG_SYSTICK					= 1
CONFIG_SLEEP_TIMER 				= 1 # implement sleep() using a timer
CONFIG_HPPS_TRCH_MAILBOX 		= 1
CONFIG_HPPS_TRCH_MAILBOX_ATF 	= 1
CONFIG_HPPS_TRCH_MAILBOX_SSW 	= 1
CONFIG_RTPS_TRCH_MAILBOX 		= 1
CONFIG_HPPS_TRCH_SHMEM			= 1
CONFIG_HPPS_TRCH_SHMEM_SSW 		= 1
CONFIG_TRCH_WDT 				= 1
CONFIG_RTPS_R52_WDT 			= 1
CONFIG_RTPS_A53_WDT 			= 1
CONFIG_HPPS_WDT 				= 1
CONFIG_TRCH_DMA 				= 1
CONFIG_RT_MMU 					= 1 # RTPS/TRCH->HPPS MMU
CONFIG_CONSOLE					= NS16550

